#!/bin/bash -e


#SBATCH --job-name EDTA
#SBATCH --time=7-00:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --output pfr_edta.stdout
#SBATCH --error pfr_edta.stderr
#SBATCH --mem=4G

full_test_flag=0

# Parse command line options
while getopts "t" opt; do
    case ${opt} in
    t )
        full_test_flag=1
        ;;
    \? )
        echo "Invalid option: $OPTARG" 1>&2
        exit 1
        ;;
    esac
done
shift $((OPTIND -1))

ml apptainer/1.1
ml nextflow/24.10.1

export TMPDIR="/workspace/$USER/tmp"
export APPTAINER_BINDPATH="$APPTAINER_BINDPATH,$TMPDIR:$TMPDIR,$TMPDIR:/tmp"

if [ $full_test_flag -eq 1 ]; then
    nextflow \
        main.nf \
        -c pfr/profile.config \
        -profile pfr,apptainer,test_full \
        -resume \
        --outdir results
else
    nextflow \
        main.nf \
        -c pfr/profile.config \
        -profile pfr,apptainer \
        -params-file pfr/params.json \
        -resume
fi
